version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    groups:
      development-dependencies:
        dependency-type: "development"
      production-dependencies-patch-updates:
        dependency-type: "production"
        update-types: [ "patch" ]
  - package-ecosystem: docker
    directory: /runtime
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    groups:
      development-dependencies:
        dependency-type: "development"
      production-dependencies-patch-updates:
        dependency-type: "production"
        update-types: [ "patch" ]
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"