[[section-introduction-and-goals]]
== Introduction and Goals

https://mthmulders.github.io/polly/[Polly] is a project for

* letting me run live polls during a talk at a conference or meetup.
* evaluating and learning certain technologies:
** https://jakarta.ee/[Jakarta EE]
** https://jakarta.ee/specifications/mvc/[Jakarta MVC]
** https://playwright.dev/java[Playwright]

=== Requirements Overview
From a functional point of view, Polly is a web application for running a live poll during a talk or event.
Consider it the digital version of the "show of hands", but with live display of what the audience voted.

From a project perspective, I use Polly to study and evaluate technology, patterns and frameworks.
The functional requirements aren't too complex, leaving me enough room for attention to quality goals.

.Main features
* Define a poll: a question with a predefined set of answers.
* Define a poll instance, that is: one particular occurrence of a poll at a particular event.
* Display an "event" view of a poll, consisting of a QR code for easy access to the voting page, and a graph that shows the live results.
** This display should be embeddable in another HTML page.
* Letting attendees vote on a poll instance.


I haven't yet decided if I want or need a management user interface for defining those polls.
For the first iteration, it may be enough to manually insert them into the persistent storage.

=== Main Quality Goals
The following list contains the most important quality goals for this application.
The full list is in <<Quality Requirements>>.

[cols="0,1,3" options="header"]
.Main Quality Goals
|===
| ID | Quality | Motivation

| QG01
| Understandability
| Functional requirements should be simple and stay simple. This allows me to focus on the other goals (learning, experimenting) as well as writing quality code.

| QG02
| Attractiveness
| Given I want to use Polly during events where I speak, the display should look good.

| QC03
| Testability
| The architecture should allow easy testing of all main building blocks.

|===

=== Stakeholders
The following lists contains the most important personas for this application.
[options="header",cols="1,2"]
.Stakeholders
|===
| Role/Name           | Goal/Boundaries

| Developers
| Developers familiar with Java who want to learn about developing modern web applications without having to learn JavaScript/Typescript and an additional web application framework or two.

| Maarten Mulders (me)
a| 1. Improving my skills as an architect and a developer. Have some real-world, working sample code when discussing "traditional" web applications or Jakarta MVC.
2. Having a convenient way to poll attendee opinions during a talk at a conference or Java user group gathering.

|===