[[section-solution-strategy]]
== Solution Strategy

Polly is a single deployable application using a relational database.

plantuml::img/structurizr-polly-container.puml[format=svg]

The architecture of Polly follows the ideas of https://en.wikipedia.org/wiki/Hexagonal_architecture_(software)[hexagonal architecture].
This means that its domain model is unaware of the technology that powers it.
Each component lives in its own https://maven.apache.org/guides/mini/guide-multiple-modules-4.html:[Maven module], which is also a https://www.oracle.com/corporate/features/understanding-java-9-modules.html[Java module].
This approach makes it easier to test a large part of the application logic in a fast and light-weight way **[QC.OE.01]**.

The core of Polly is its Domain Model, which is completely agnostic of any framework or library.
It applies a few tactical patterns from Domain Driven Design.
You will find Repositories, rich Entities and Value Objects.

Since the Domain is technology-agnostic, some parts cannot be implemented in the Domain.
That's why the Infrastructure provides implementations based on the selected technology stack.
For instance, it provides implementations of the Repositories based on the Jakarta Persistence API.

The Web application is responsible for generating the web-based user interface.
It uses Krazo to deliver fast, light-weight web pages rather than requiring users to download a large bundle of JavaScript **[QC.PF.01]**, **[QC.PF.02]**.

To bring it all together without introducing undesired dependencies, the Application module packages all these components together.
It creates a Web Archive (WAR) using https://maven.apache.org/plugins/maven-war-plugin/overlays.html[overlays], that can be deployed to any Jakarta EE 10-compatible application server **[QC.OE.01]**.
