name: SonarCloud analysis

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Cache Maven packages
        uses: actions/cache@v4.0.1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set up JDK
        uses: actions/setup-java@v4.1.0
        with:
          java-version: 17
          distribution: 'adopt'

      - name: SonarCloud Scan
        run: |
          mvn -B -P sonarcloud -Dsonar.token=$SONAR_TOKEN --no-transfer-progress -pl \!app,\!test,\!docs verify sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
